name: tunai_mudah
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.0.0+2
  get: 4.6.6
  persistent_bottom_nav_bar_v2: ^5.2.3
  flutter_config: ^2.0.2
  flutter: 
    sdk: flutter
  dropdown_textfield: ^1.0.8
  flutter_screenutil: ^5.9.0
  envied: ^0.5.4+1
  dio: ^5.4.3+1
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.9
dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
    

flutter: 
  uses-material-design: true
  assets:
  - assets/images/getstarted.png
  - assets/images/getstarted2.png
  - assets/images/getstarted3.png
  - assets/images/sign.png
  - assets/images/signup.png
  - assets/icons/logo.png
  - assets/images/mask_circle.png
  - assets/icons/pulsa.png
  - assets/icons/games.png
  - assets/icons/air.jpg
  - assets/icons/asuransi.jpg
  - assets/icons/bpjs.png
  - assets/icons/invest.png
  - assets/icons/pln.png
  - assets/icons/scan.png
  - assets/icons/topup.jpg
  - assets/icons/tf.png
  - assets/icons/wifi.png
  - assets/icons/visa.png
  - assets/icons/profile.jpg
  - assets/images/transaksi.png

